### ISSUE TITLE
Crash when font mods enabled

### ISSUE THREAD

**Issue by liolok** [gimme/item-meta#1]
```
Assert failure 'BREAKPT:' at ../source/game/render/BitmapFontManager.cpp(98)
```

Tested font mod: https://github.com/liolok/TsangerXuansan

Seems about `GLOBAL.DEFAULT_FALLBACK_TABLE` and `GLOBAL.DEFAULT_FALLBACK_TABLE_OUTLINE`

**Comment by gimme** [comment]
I can't seem to replicate the issue; I can get into game with both functioning together.

But I would love to know if there is a better way to load the font.

**Comment by liolok** [comment]
> if there is a better way to load the font.

I have no idea either, seems adding icons.zip to fallback table is the right way.

Maybe my issue is platform related, I'm on Arch Linux.

**Comment by liolok** [comment]
```
[00:01:33]: [C](-1): SetupFontFallbacks

[00:01:33]: [string "../mods/TsangerXuansan-master/modmain.lua"](31): RegisterFonts

[00:01:33]: [string "../mods/TsangerXuansan-master/modmain.lua"](66): ?
```

Tested on Windows, full log at ~https:// /client_log.c8UI9f.txt~

**Comment by gimme** [comment]
Ok, I think I've figured it out and just published a fix.

The problem was that I would add my font alias to `DEFAULT_FALLBACK_TABLE` before the font itself was loaded. If another mod then tried to load a font using `DEFAULT_FALLBACK_TABLE` as fallback, the game would crash because it couldn't find my actual font.

I've solved it by making sure it appropriately calls the `LoadFonts` function and only _then_ makes the font accessible.

**Comment by gimme** [comment]
I think this makes it work as expected from my end, but it won't immediately make the mods compatible. I'll open an issue on the other repo.

**Comment by liolok** [comment]
Huge thanks for your help! Seems no problem by now.

**Comment by gimme** [comment]
No worries. Thank you too
